INCLUDE(CMakeForceCompiler)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)

set(TOOLCHAIN_DIR /usr/local/toolchains)
set(TOOLCHAIN_TYPE arm-mac-linux-gnueabihf)
set(CMAKE_SYSROOT ${TOOLCHAIN_DIR}/${TOOLCHAIN_TYPE}/${TOOLCHAIN_TYPE}/sysroot)
set(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/${TOOLCHAIN_TYPE}/bin/${TOOLCHAIN_TYPE}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/${TOOLCHAIN_TYPE}/bin/${TOOLCHAIN_TYPE}-g++)
set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_DIR}/${TOOLCHAIN_TYPE}/)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CONSOLE 1)

